cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^signup/$', views.signup, name = 'signup'),
    url(r'^about/$', views.about, name='about'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^home/$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True, help_text='Required.')
    first_name = forms.CharField(required = True)
    last_name = forms.CharField(required = True)

    class Meta:
        model = User #model User comes with username, email, first name, last name , pass1 and pass2 fields
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )

    def save(self, commit = True):
        user =  super(RegistrationForm, self).save(commit = False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name =  self.cleaned_data['last_name']
        user.email =  self.cleaned_data['email']

        #note password is saved automatically in User models original save()
        # function, everything else needs to be done manually as done above
        if commit:
            user.is_active = True
            user.save()

            return user

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from cart.forms import CartAddProductForm
from . forms import RegistrationForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

def signup(request):

    if request.method == 'POST':

        form = RegistrationForm(request.POST)

        if form.is_valid():

            user = form.save()

            user.save()

            return redirect('/home/')

    else:
        form = RegistrationForm()


    return render(request, 'shop/signup.html', {'form':form})

def about(request):
    return render(request, 'shop/about.html')

shop/templates/shop/about.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Talla Global - About us
{% endblock %}

{% block content %}

<div class="row" style="margin-top: 6%">

<div class="col-md-4" align = "center">

<h4>Modesty</h4>
<p>Humbleness proves that we’re not always right, we don’t have all the answers, and we know it. We’re no less human than the people who work for us, and we’re not afraid to ask for help.</p>

</div>

<div class="col-md-4" align = "center">
<h4>Honesty</h4>
  <p>
Integrity is the cornerstone of all the above. We set and observe high ethical standards and do the right thing. We perform duty of care, not only to our customers, other stakeholders and to the communities we serve, but also to our colleagues and ourselves.
 </p>

</div>

<div class="col-md-4" align = "center">

  <h4>Mission</h4>
  <ol>Offering quality and comprehensive solutions to our customers.<ol>
  <ol>Building customer loyalty and long-term partnership with our suppliers<ol>

</div>

</div>
<br>

{% include "shop/highchart.html" %}


{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'shop/navbar.html' %}

<div class="float-right">
<div class="container" >
    <div class="row" style="margin-top: 2%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    <i class="fas fa-shopping-cart"></i>
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} item{{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    <i class="fas fa-shopping-cart"></i> Your cart is empty
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
</div>
<br><br>
{% block content %}


{% endblock %}

{% include "shop/footer.html" %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5b67c810e21878736ba2a630/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

</body>
</html>

shop/templates/shop/carousel.html
{% load static %}
<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
    <li data-target="#demo" data-slide-to="3"></li>
    <li data-target="#demo" data-slide-to="4"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
  <img style="width:1300px; height:400px;top: 0px; left: 0px;margin-top: 0px; margin-left: 0px;" src="{% static "images/f1.jpg"  %}" alt="My image"  />
      <div class="carousel-caption">

      </div>
    </div>
    <div class="carousel-item">
  <img style="width:1300px; height:400px;top: 0px; left: 0px;margin-top: 0px; margin-left: 0px;" src="{% static "images/f2.jpeg"  %}" alt="My image"  />
      <div class="carousel-caption">

      </div>
    </div>
    <div class="carousel-item">
  <img style="width:1300px; height:400px;top: 0px; left: 0px;margin-top: 0px; margin-left: 0px;" src="{% static "images/f3.jpeg"  %}" alt="My image"  />
      <div class="carousel-caption">

      </div>
    </div>

    <div class="carousel-item">
  <img style="width:1300px; height:400px;top: 0px; left: 0px;margin-top: 0px; margin-left: 0px;" src="{% static "images/f4.jpg"  %}" alt="My image"  />
      <div class="carousel-caption">

      </div>
    </div>

    <div class="carousel-item">
  <img style="width:1300px; height:400px;top: 0px; left: 0px;margin-top: 0px; margin-left: 0px;" src="{% static "images/f5.jpg"  %}" alt="My image"  />
      <div class="carousel-caption">

      </div>
    </div>

  </div>

  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

shop/templates/shop/footer.html
{% load static %}

<div class="row" style="background-color:#322f30; margin: 6px;" id="contact">

<div class="col-md-4"  >

<p style="color:white"><i class="fas fa-sign-in-alt"></i> Phone:  +254702290881</p>
<p style="color:white"><i class="fas fa-envelope"></i> Email:  info@tallaglobal.com</p>
<p style="color:white"><i class="fab fa-skype"></i> Skype: Talla Global</p>

</div>

<div class="col-md-4" >

  <h5 style="color:white">Kenya Office</h5>
  <p style="color:white">Mark Square, 5th Floor, Block 3</p>
  <p style="color:white">Chiromo Road, Westlands,</p>
  <p style="color:white">Nairobi, Kenya.</p>
  <p style="color:white"><i class="fas fa-sign-in-alt"></i> Phone:  +254702290881</p>
  <p style="color:white"><i class="fas fa-envelope"></i> Email:  info@tallaglobal.com</p>
  <p style="color:white"><i class="fab fa-skype"></i> Skype:  Tallaglobal</p>
  <br>
  <br>
  <p style="color:white"> <i class="fab fa-facebook-square"></i> <i class="fab fa-twitter-square"></i> <i class="fab fa-linkedin"></i> </p>

</div>

<div class="col-md-4" >

  <h5 style="color:white">USA Office</h5>
  <p style="color:white">10265 Hill Top</p>
  <p style="color:white">Dallas, USA 20162</p>
  <p style="color:white"><i class="fas fa-sign-in-alt"></i> Email:  usa@tallaglobal.com</p>
  <p style="color:white"><i class="fab fa-skype"></i> Skype:  Tallaglobal</p>
  <br>
  <br>  <br>
    <br>  <br>
      <br>  <br>
        <br>  <br>
          <br>

</div>

</div>

shop/templates/shop/highchart.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <div id="container"></div>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'General Statistics of our Served Clients'
        },
        xAxis: {
            categories: ['2014', '2015', '2016', '2017', '2018']
        },
        series: [{
            name: 'Food ',
            data: [50, 75, 101, 177, 346]
        }, {
            name: 'House',
            data: [42, 66, 128, 190, 248]
        }, {
            name: 'Electronics',
            data: [40, 67, 156, 236, 324]
        }]
    });
  </script>
</body>
</html>

shop/templates/shop/navbar.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;" >
  <div class="container">
    <a class="navbar-brand" href="{% url 'shop:product_list' %}">Talla Global</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'shop:product_list' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about/">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact">Contact</a>
        </li>

        {% if request.user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="#"><i class="far fa-user"></i> {{ request.user.username }} </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> logout </a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/accounts/login/"><i class="fas fa-sign-in-alt"></i> Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/signup/"><i class="fas fa-user-plus"></i> Sign up</a>
        </li>

        {% endif %}

      </ul>
    </div>
  </div>
</nav>

shop/templates/shop/signup.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}

<div align = "center" style="margin-top: 6%">
<div class="card border-success mb-3" style="max-width: 18rem;">

  <div class="card-header bg-info border-success" align = "center">Register new account</b></div>

  <div class="card-body text-success" align = "center">
    <hr>
    <form method="post" align = "center">
      {% csrf_token %}
      {% for field in form %}
     <p>
      <div style="color:blue"> <b>{{ field.label_tag }} </b></div>
       {{ field }}

       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </p>
    {% endfor %}
      <br>

      <button class="btn btn-primary btn-lg"  type="submit"  >Signup</button>

    </form>
  </div>

</div>
</div>

{% endblock %}